### ISSUE TITLE
Command "map" and "raw_command" - what do they do?

### ISSUE THREAD

**Issue by alexdom** [rytilahti/python-mirobo#19] opened 2017-06-22 05:34 UTC
What do these command do? I hoped this return a JPEG of cleaning map, like iPad Mi app does, but it s not:

`-> # mirobo map`   
```
['retry']
```
Any detailed information about how to use this command:

`-> # mirobo raw_command`
```
Usage: mirobo raw_command [OPTIONS] CMD [PARAMETERS]

Error: Missing argument "cmd".
```

**Comment by rytilahti** [comment] 2017-06-22 18:27
raw_command does as explained in the README and/or in --help, namely allows one to give direct commands to the device without implementing them first. That can be used to test out implementations for other types of devices / new commands without directly implementing them.

The map gives the token which is used by the mobile app to fetch the map from the remote server, it is of no use currrently. When it says retry, it just means that your robot cannot fetch the token (meaning that it is probably not connected to the internet). As this is not a bug, I'm closing it. If there's something to be fixed in the documentation related to these features (and others), PRs are very welcome.

**Closed by rytilahti** 2017-06-22 18:27 UTC

**Comment by otbe** [comment] 2017-06-26 14:06
Sorry for jumping into this issue.

If I get the map token via ```mirobo map``` how can I pull the map down the wire? A sample (http?) request would be nice. Thank you very much!

**Comment by rytilahti** [comment] 2017-06-26 19:09
Not a problem. One gets some sort of token by calling this, that's why I left it in place if/when someone figures out how it can used. Personally I haven't looked at all into the communications between the robot and the servers of xiaomi, besides that it's using an encrypted connection.

**Comment by otbe** [comment] 2017-06-27 05:14
I understand. I hoped it would be easy, so I can inline the map into openHAB :) 

Thank you very much.

**Comment by marcelrv** [comment] 2017-06-27 12:36
@otbe for Openhab you may be interested in pulling this: https://marketplace.eclipse.org/content/openhab-xiaomi-vacuum-binding
No support for pulling the maps either though :( but does give you easy way for openhab
